#!/usr/bin/env ruby
system 'echo "Rails Best Practices" && rails_best_practices'
system 'echo "RuboCop" && rubocop'
system 'echo "Reek" && reek' 
system 'echo "Flog" && flog app'
system 'echo "Flay" && flay app'
system 'echo "Brakeman" && brakeman'